# 釣果情報ホームページを巡回する時のスリープ時間(秒)
interval = 5

# 巡回する釣果情報ポイントホームページのリスト、
# https://www.fishing-v.jp/choka/choka_detail.php?s={id}"
# で表示させるURL パラメータの各ポイント id を指定する
[[area]]

name = 'Daikoku'
id = 11285
last_page = 88

[[area]]

name = 'Isogo'
id = 11286
last_page = 97

[[area]]

name = 'Honmoku'
id = 11284
last_page = 58

