# 釣果情報ホームページを巡回する時のスリープ時間(秒)
# interval = 3

# 釣果サイトページ巡回の最大ページ数
# max_page = 1000

# 巡回する釣果情報ポイントホームページのリスト、
# http://{施設名}.yokohama-fishingpiers.jp/choka.phpで表示させるURLを指定する
[[area]]

name = 'daikoku'

[[area]]

name = 'isogo'

[[area]]

name = 'honmoku'

